learning_rate: 1e-3
epochs: 85

optimizer:
  weight_decay: 1e-4

scheduler:
  factor: 0.1
  patience: 5
  step: 15
  gamma: 0.1

dataloader:
  batch_size: 16
  num_workers: 1

checkpoint:
  epochs_to_pass: 5

train_test:
  test_perc: 0.2
  test_splits: 4
