defaults:
  - _self_
  - data: segmentations
  - architecture: Unet
  - model: training
  - loss_function: dice
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

random_seed:
  seed: 23

device: cuda

hydra:
  output_subdir: null
  run:
    dir: logs


