defaults:
  - _self_
  - mode: classification
  - training: classification_regime
  - segmentation_architecture: FPN
  - classification_architecture: efficientnet-b0
  #- override hydra/launcher: joblib
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

random_seed: 64

device: cuda

#hydra:
#  launcher:
#    # override the number of jobs for joblib
#    n_jobs: 2
hydra:
  job:
    chdir: True
#  output_subdir: results
#  run:
#    dir: .


