defaults:
  - _self_
  - mode: segmentation
  - training: segmentation_regime
  - segmentation_architecture: UnetPlusPlus
  - classification_architecture: efficientnet-b0
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

random_seed: 23

device: cuda

#hydra:
#  output_subdir: null
#  run:
#    dir: .


